// Family B — one simulated AI answer, sectioned so any prefix reads as a complete answer.
export default {
  id: "b",
  topic: "Minimum wage and employment",
  question: "Does raising the minimum wage cause job losses?",
  sections: [
    "The short answer is that economists genuinely disagree, and the evidence points in more than one direction. Decades of research have not produced a single settled number for how minimum wage increases affect employment. What the literature does suggest is that the size of the increase matters enormously. Modest increases in labor markets where wages already sit well above the new floor tend to show small or hard-to-detect employment effects. Large increases relative to local wages carry considerably more risk. Anyone who tells you the question is definitively resolved in either direction is overstating what the research can actually support at this point.",

    "The classic argument against raising the minimum wage comes from the standard supply and demand model. If a wage floor is set above what the market would otherwise pay, employers respond by buying less labor, and some workers who would have been hired at the lower wage are not hired at all. This is the intuition behind the claim that minimum wage increases cost jobs, and it is a reasonable starting point. The model is clean and easy to teach. Its predictions depend, however, on the assumption that low-wage labor markets behave competitively, and that assumption is doing a great deal of work.",

    "A competing model treats employers as having some wage-setting power, a condition economists call monopsony. When a small number of firms dominate hiring in an area, or when workers face real costs in switching jobs, employers can pay less than the value a worker adds and still fill their positions. In that setting a moderate wage floor can raise pay without reducing employment, and can even increase it, because firms that were holding wages down to limit their own costs now find it worthwhile to hire more people. The monopsony model is not a fringe view. It appears throughout modern labor economics.",

    "The empirical turn came in the early 1990s, when researchers began comparing employment on either side of a state border after one state raised its minimum wage and its neighbor did not. A widely discussed study of fast food restaurants using that design found no evidence that employment fell, and in some specifications it appeared to rise slightly. The finding was contested almost immediately, including by researchers who reanalyzed payroll records and reached different conclusions. What that episode changed was less the answer than the method. Credible comparison groups, rather than national time trends, became the standard for the field.",

    "Where the profession has landed is roughly this. Most labor economists now accept that the moderate increases enacted in the United States over recent decades produced employment effects that were small, and often too small to detect reliably in the available data. Disagreement persists about whether small means near zero or merely modest, and about what happens at higher floors that nobody has studied at length. Surveys of economists tend to show a split rather than a consensus, with more agreement about direction than about magnitude. It is worth treating confident claims from either camp with a degree of caution.",

    "Employment is not the only margin that can move. A firm facing a higher wage bill may keep the same number of workers on payroll while cutting scheduled hours, tightening shifts, or reducing overtime. Studies that count jobs alone can miss this entirely, which is one reason results vary with the outcome being measured. Research drawing on scheduling and hours data has found reductions in hours in some settings even where headcount held steady. For a worker, the practical question is take home pay, so hours effects matter fully as much as whether the job itself exists at all.",

    "Firms have several ways to absorb higher labor costs besides cutting staff. They can raise prices modestly, particularly in restaurants and other service businesses where customers are local and competitors face the same cost increase. They can accept thinner profit margins. They can benefit from lower turnover, since better paid workers quit less often and recruiting and training a replacement is expensive. Some evidence suggests turnover savings offset a meaningful share of the added cost. Firms may also raise their hiring standards, which changes who ends up getting the job rather than how many jobs are on offer.",

    "The effects, whatever their true size, are not spread evenly across the workforce. Minimum wage workers are concentrated among younger workers, workers without college degrees, and employees in food service, retail, and personal care. Studies frequently find that any measurable employment response appears first among teenagers and among workers with the least experience, since they are the ones whose current productivity sits closest to the new floor. This matters for policy, because the group most likely to gain from higher pay overlaps substantially with the group that is most exposed to any pullback in hiring.",

    "One concept does more work in this literature than almost any other, and that is the bite of the minimum wage, meaning its level relative to the typical wage in the local labor market. A floor set at half the local median is a very different policy from one set near the median, even when the dollar figure is identical. Most of the credible research covers increases in the lower part of that range. That is a real limit on what the evidence can tell us, and it is the honest place to leave the general version of the question.",

    "Geography explains much of why a single national answer proves elusive. A wage floor that barely binds in an expensive coastal city may sit above the going rate for a large share of jobs in a rural county in a low cost state. The same federal increase therefore amounts to a mild adjustment in one place and a substantial shock in another. This is part of why many economists prefer state and local minimums, or indexing to regional wage levels, over a uniform national number. It also means that national studies can end up averaging together very different local experiences.",

    "Employer concentration gives the monopsony story real force in some places. In small towns and rural areas, a single hospital, processing plant, or large retailer may account for much of the available work, and a worker unhappy with the pay has few nearby alternatives. Measures of local hiring concentration have become easier to build using modern job postings and payroll data, and areas that look more concentrated tend to show lower wages relative to productivity. In such markets a wage floor is more likely to raise pay without costing jobs, since the employer generally has some room to absorb it.",

    "Much of the professional disagreement is methodological rather than ideological. The core difficulty is constructing a believable counterfactual: what would employment in a given place have done had the wage not risen? Different answers follow from different comparison groups. Border county designs, synthetic control methods, and approaches that track the whole distribution of wages each embed assumptions about which places make good stand ins for one another. Researchers who defend one design usually have principled objections to the others. Readers who want a single number will find that the number moves with the method, which is itself an informative result.",

    "Reviews that pool many studies together add a further complication. Meta analyses of the minimum wage literature have found signs of publication bias, the tendency for results confirming expectations to be written up and accepted more readily than results that do not. Corrections for that bias generally pull estimated job losses toward zero, though the corrections themselves are contested and they depend on modeling choices. The broader lesson is that counting studies on each side is a poor way to settle the question, since the population of published studies is not a random sample of the research that was actually carried out.",

    "More recent work has benefited from administrative records that follow individual jobs over time rather than counting employment at a single point. Linked employer and employee data make it possible to see whether particular low-wage positions disappeared, whether the same workers moved into better paying jobs, and how earnings evolved over time for the people the policy was meant to help. These datasets have narrowed some of the longstanding disputes in the field and sharpened others. They tend to show meaningful earnings gains for workers who stay employed, alongside smaller and more contested effects on the total number of jobs.",

    "A useful distinction separates the number of low-wage jobs from the level of total employment. Some studies find that jobs paying below the new floor decline sharply, as they must by definition, while jobs paying just above it increase by a similar amount, leaving overall employment close to unchanged. Others find the offset incomplete, implying that some of those positions vanished rather than moving up the wage ladder. The disagreement is essentially about whether the missing bottom of the wage distribution reappears higher up, and that turns out to be a demanding thing to measure with any real precision.",

    "Time horizon changes the picture as well. Employers can adjust more thoroughly over years than over months, and higher labor costs strengthen the case for self service kiosks, scheduling software, and other capital that substitutes for low-wage labor. Some research finds that jobs built around the most routine and predictable tasks are the most exposed to this kind of substitution. Most studies, however, examine a window of one to three years after an increase, which may be too short to capture slower adjustments. Long run effects are less well studied than short run effects, and that gap is widely acknowledged.",

    "Business dynamics offer another channel worth understanding. Higher labor costs press hardest on firms already operating near the margin, and some research finds that minimum wage increases raise the exit rate of lower quality or less productive establishments while leaving stronger ones intact. If new entrants are more efficient than the businesses that close, average productivity in a sector can rise even as individual firms fail. Whether that counts as harm depends on what happens to the displaced workers afterward, which is a separate empirical question, and one with noticeably less evidence behind it than the headline employment question itself.",

    "The employment question is ultimately a means to a larger one: does a higher minimum wage leave low income households better off? Most analyses find that total earnings among affected workers rise, because the wage gain for the many outweighs lost hours for the few. Effects on measured poverty rates are more modest than the earnings figures alone would suggest, partly because many minimum wage workers live in households that are not poor, and many poor households have no wage earner at all. Reasonable people weigh a broad and modest gain against a smaller, more concentrated loss quite differently.",

    "Prices absorb part of the cost, and that shapes who ultimately pays for the increase. Studies of restaurant menus after minimum wage increases typically find modest price rises concentrated in labor intensive sectors and spread across a broad base of customers. Because the affected industries make up a small share of the overall economy, the effect on general inflation appears fairly limited. Price increases also erode part of the real gain to workers, though by no means all of it, since low-wage workers spend only a fraction of their income at the businesses most directly affected by the change.",

    "Economists have looked for direct evidence of employer wage-setting power rather than inferring it from minimum wage results alone. One approach examines how many workers a firm loses when it cuts pay relative to its competitors, since a truly competitive employer would expect to lose nearly all of them. Field experiments that vary posted wages in online labor markets have found that firms retain far more workers than the competitive model would predict. Findings of this kind have made the monopsony explanation considerably more respectable, though its strength almost certainly varies a great deal across industries, regions, and individual occupations.",

    "Higher pay can also pull people into the labor market. When wages rise, some people who were not previously looking for work begin searching, and employers often report filling their open positions faster. Research on vacancy duration and application rates finds that better paying jobs attract more applicants, which reduces the cost of recruiting. This complicates simple job loss accounting, since the number of positions and the number of people seeking them can both respond at once. A policy that leaves total employment roughly flat may still change who ends up holding the jobs and how quickly they get filled.",

    "International experience adds useful variation. The United Kingdom introduced a national minimum wage in the late 1990s and has raised it substantially since, guided by an independent commission that reviews the available evidence before recommending each increase and usually moves gradually. Evaluations there have generally found limited employment effects, though the cautious and incremental approach taken there makes it as much a test of gradualism as of the policy itself. Several European countries rely on sector level bargaining rather than statutory floors, which produces high effective minimums through an entirely different mechanism and makes direct comparison awkward.",

    "Design details matter more than the headline number usually suggests. Phase-in schedules spread the adjustment over several years and give employers time to plan around it. Regional variation, whether written into the law or achieved through state and local action, lets the floor track local wage levels. Separate rates for teenagers or trainees exist in several countries and are intended to protect entry-level hiring, though they raise fairness concerns of their own. Tipped minimum wages, which are common in the United States, create a distinct set of questions about enforcement and about who bears the risk of a slow night.",

    "Enforcement determines how much of the law actually reaches workers. Research on wage theft finds that a meaningful share of workers entitled to the minimum are paid less than it, through unrecorded hours, misclassification as independent contractors, or simple nonpayment. Compliance tends to be weaker in industries with many small employers, high turnover, and workers who are reluctant to complain. An increase that simply goes unenforced delivers neither the intended gains nor the predicted costs, so studies of legal minimums and studies of actual pay can diverge. Enforcement capacity is rarely funded in proportion to the size of an increase.",

    "For any specific proposal, a handful of factors do most of the work in predicting the outcome. How large is the increase relative to the local median wage? How quickly does it take effect? How tight is the local labor market at the moment it lands? How concentrated are the employers who will actually have to pay it? A moderate increase phased in over several years in a high wage city is a very different policy from an immediate doubling in a low wage region, and the existing research offers far more guidance about the first case than about the second.",

    "Part of why this argument persists is that it is not purely empirical. Even if everyone agreed completely on the numbers, people would still weigh the resulting outcomes quite differently. Someone who gives most weight to the workers who receive a raise reaches a different conclusion from someone focused on the worker who cannot find a first job. Views about whether businesses or taxpayers should support low earners, and about alternatives such as wage subsidies and earned income tax credits, shape which evidence feels decisive. Empirical findings can inform that judgment, but they do not settle it on their own.",

    "Several questions remain genuinely open. Very high minimums relative to local wages are still thinly studied, because relatively few jurisdictions have tried them and fewer still have been observed for long enough to matter. Long run effects on automation, business formation, and career trajectories are harder to identify than short run employment counts. Economy-wide effects, including how higher wages at the bottom ripple through spending and prices, are difficult to capture in studies of single localities. New data and a steady stream of new state-level increases will keep producing evidence, and the picture may well look different a decade from now.",

    "The honest bottom line is that raising the minimum wage does not automatically cost jobs, and it is not automatically free of cost either. The weight of recent evidence suggests that moderate increases in labor markets where the new floor stays well below the local median produce small employment effects, alongside real earnings gains for the workers affected. The risk grows as the floor rises toward the middle of the local wage distribution, where the evidence is thin. That framing is less satisfying than a simple yes or no, but it is a fair reflection of what the research currently supports.",
  ],
};
