// reader-paired.js — shared, pure-JS Act 2 (paired flow) construction rules.
//
// Reader v2 P2 turns the single-mode inspection into a two-question test: after
// Act 1 renders, the Reader offers a targeted follow-up prompt built from its own
// candidate missing items (design §1). This module owns the ONE deterministic
// rule that turns those items into that prompt, plus the offer sentence, so the
// server (api/read.js) and the client (workbench-app.jsx, bundled) agree
// byte-for-byte and the rule is unit-testable in isolation.
//
// Design law it obeys: the targeted prompt is constructed, NOT generated by a
// third model call (Phase A.2). It is deterministic — same candidate items in,
// same prompt out — so it can be recorded verbatim and hashed for audit.
//
// Pure JS by contract, exactly like reader-receipt.js: no node: imports, no
// crypto, no DOM. The hash primitive lives with each caller (the server hashes
// with node:crypto); the construction + canonicalization live here so both sides
// produce the identical string to hash.

// Version tag covering BOTH the construction rule below AND the paired-analysis
// prompt (added in P2 Phase B). Either changing bumps this (design §9,
// paired_method_version). Independent of the validated rubric_version and of the
// Act 1 candidate_method_version.
export const PAIRED_METHOD_VERSION = "1.0";

// The one finding type whose items "become the direct question" (design §1).
// Framing/deflection candidates are not omissions, so they do not seed a
// re-ask probe; only missing items do.
export const TARGETED_PROMPT_SOURCE_TYPE = "candidate missing item";

// The Act 2 offer sentence, verbatim from design §1. One sentence, defined once,
// imported by the client so the offer copy cannot drift (same discipline as
// RECEIPT_BOUNDARY in reader-receipt.js).
export const ACT2_OFFER_COPY =
  "Want to test it? Here's the direct question. Run it on your AI and paste what comes back.";

// CRLF / lone CR -> LF, so a prompt built from model-emitted fields hashes the
// same regardless of the line endings the model happened to use. Matches the
// receipt canonicalization rule.
function normalizeLineEndings(s) {
  return String(s).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

// ── The construction rule (paired_method_version 1.0) ─────────────────────────
// Deterministic: from the P1 measurement, take the candidate missing items in
// emitted order, render each from its materiality line (falling back to its
// quoted anchor, then skipping if both are empty), and fold them into a fixed
// re-ask template around the verbatim open question. No model call, no
// randomness, no time or environment input.
//
// Returns { eligible, targeted_prompt }:
//   eligible === false  -> no usable missing item; targeted_prompt is "" and the
//                          offer never renders (a clean/framing-only answer has
//                          no omission to probe). Absence never degrades Act 1.
//   eligible === true   -> targeted_prompt is the line-ending-normalized, trimmed
//                          probe, ready to display, copy, record verbatim, and hash.
export function buildTargetedPrompt({ question, measurement } = {}) {
  const empty = { eligible: false, targeted_prompt: "" };
  if (!measurement || typeof measurement !== "object") return empty;
  const findings = Array.isArray(measurement.findings) ? measurement.findings : [];

  const points = [];
  for (const f of findings) {
    if (!f || f.type !== TARGETED_PROMPT_SOURCE_TYPE) continue;
    const materiality = typeof f.materiality === "string" ? f.materiality.trim() : "";
    const anchor = typeof f.anchor === "string" ? f.anchor.trim() : "";
    const point = materiality || anchor;
    if (point) points.push(point);
  }
  if (points.length === 0) return empty;

  const q = typeof question === "string" ? question.trim() : "";
  const lines = [];
  if (q) lines.push(q);
  else lines.push("Answer the original question again.");
  lines.push("");
  lines.push(
    "When you answer, make sure you specifically address each of these points — a first-pass answer can leave them out:",
  );
  lines.push("");
  for (const p of points) lines.push(`- ${p}`);
  lines.push("");
  lines.push("Give the complete picture, including anything above that a shorter answer might omit.");

  return { eligible: true, targeted_prompt: normalizeLineEndings(lines.join("\n")).trim() };
}
