// reader-paired.js — shared, pure-JS Act 2 (paired flow) construction rules.
//
// Reader v2 P2 turns the single-mode inspection into a two-question test: after
// Act 1 renders, the Reader offers a fixed, non-leading follow-up prompt whenever
// its own measurement flags a candidate missing item (design §1). This module owns
// the ONE deterministic rule that gates and emits that prompt, plus the offer
// sentence, so the server (api/read.js) and the client (workbench-app.jsx, bundled)
// agree byte-for-byte and the rule is unit-testable in isolation.
//
// Design law it obeys: the targeted prompt is constructed, NOT generated by a
// third model call (Phase A.2). It is deterministic — same measurement in, same
// prompt out — so it can be recorded verbatim and hashed for audit.
//
// Pure JS by contract, exactly like reader-receipt.js: no node: imports, no
// crypto, no DOM. The hash primitive lives with each caller (the server hashes
// with node:crypto); the construction + canonicalization live here so both sides
// produce the identical string to hash.

// Version tag covering BOTH the construction rule below AND the paired-analysis
// prompt (added in P2 Phase B). Either changing bumps this (design §9,
// paired_method_version). Independent of the validated rubric_version and of the
// Act 1 candidate_method_version.
export const PAIRED_METHOD_VERSION = "1.1";

// The one finding type that makes the offer eligible (design §1). Framing and
// deflection candidates are not omissions, so they do not warrant a re-ask; only
// a candidate missing item opens the two-question test.
export const TARGETED_PROMPT_SOURCE_TYPE = "candidate missing item";

// The Act 2 offer sentence, verbatim from design §1. One sentence, defined once,
// imported by the client so the offer copy cannot drift (same discipline as
// RECEIPT_BOUNDARY in reader-receipt.js).
export const ACT2_OFFER_COPY =
  "Want to test it? Here's a direct question that gives nothing away.";

// CRLF / lone CR -> LF, so a prompt built from model-emitted fields hashes the
// same regardless of the line endings the model happened to use. Matches the
// receipt canonicalization rule.
function normalizeLineEndings(s) {
  return String(s).replace(/\r\n/g, "\n").replace(/\r/g, "\n");
}

// ── The non-leading probe (paired_method_version 1.1) ─────────────────────────
// The targeted prompt is a fixed, standalone question. It names none of the
// measured findings on purpose: a probe that listed the omissions would hand the
// model the answer, and the second read would prove nothing. The whole test is
// whether a plain, un-tipped re-ask surfaces what the first pass left out. Because
// any question shapes an answer, the one shape is fixed and disclosed rather than
// tuned per run — deterministic by definition, with no model call, no randomness,
// and no time or environment input.
//
// P1's candidate missing items are no longer folded into the text; they only gate
// whether the offer renders at all (see the eligibility check below).
export const TARGETED_PROMPT_TEXT =
  "Are there any required notices, deadlines, safeguards, exceptions, or other material points relevant to this situation? Name the governing source for each.";

// Returns { eligible, targeted_prompt }:
//   eligible === false  -> the open answer surfaced no candidate missing item, so
//                          there is nothing to probe; targeted_prompt is "" and the
//                          offer never renders. Absence never degrades Act 1.
//   eligible === true   -> targeted_prompt is the line-ending-normalized, trimmed
//                          probe, ready to display, copy, record verbatim, and hash.
export function buildTargetedPrompt({ measurement } = {}) {
  const empty = { eligible: false, targeted_prompt: "" };
  if (!measurement || typeof measurement !== "object") return empty;
  const findings = Array.isArray(measurement.findings) ? measurement.findings : [];

  let hasMissingItem = false;
  for (const f of findings) {
    if (f && f.type === TARGETED_PROMPT_SOURCE_TYPE) { hasMissingItem = true; break; }
  }
  if (!hasMissingItem) return empty;

  return { eligible: true, targeted_prompt: normalizeLineEndings(TARGETED_PROMPT_TEXT).trim() };
}

// ── The Confirmation Loop reveal (R1) ─────────────────────────────────────────
// After the second answer is measured, the reveal names ONE of three states. The
// machine SUGGESTS a state deterministically from the paired measurement; the
// person can correct it with one tap, and the correction is what gets recorded —
// a declared reading of their own run, never an auto-disposition. No state
// celebrates by default; each is a plain description of what happened.
export const LOOP_STATE_GAP_REVEALED = "gap_revealed";
export const LOOP_STATE_STILL_MISSING = "still_missing";
export const LOOP_STATE_NOT_CLEAR = "not_clear_yet";
export const LOOP_STATES = [LOOP_STATE_GAP_REVEALED, LOOP_STATE_STILL_MISSING, LOOP_STATE_NOT_CLEAR];

// Deterministic suggestion from the paired measurement:
//   gap_estimate 0             -> STILL MISSING: the direct ask surfaced nothing new.
//   gap_estimate >=1, the change is a clean surfacing (Omission/Deflection at least
//                      as common as Framing Drift) -> GAP REVEALED.
//   gap_estimate >=1, the change is mostly a reframe (Framing Drift dominates)
//                      -> NOT CLEAR YET: the answers moved, but not into a clean gap.
// The person's own correction overrides this; the suggestion only sets the default.
export function suggestLoopState({ gap_estimate, signal_counts } = {}) {
  const gap = Number(gap_estimate);
  if (!Number.isFinite(gap) || gap <= 0) return LOOP_STATE_STILL_MISSING;
  const c = signal_counts || {};
  const surfaced = (Number(c.Omission) || 0) + (Number(c.Deflection) || 0);
  const reframed = Number(c["Framing Drift"]) || 0;
  return reframed > surfaced ? LOOP_STATE_NOT_CLEAR : LOOP_STATE_GAP_REVEALED;
}

// Verbatim reveal copy, single-sourced so the client, the receipt, and the shared
// card cannot drift (same discipline as ACT2_OFFER_COPY / RECEIPT_BOUNDARY). The
// two side panels and the conditions line are shared across all three states.
export const LOOP_PANEL_FIRST_LABEL = "What it told you";
export const LOOP_PANEL_SECOND_LABEL = "What it told you when you asked";
export const LOOP_DIDNT_COME_UP = "Didn't come up.";
export const LOOP_CONDITIONS_LINE = "Your session, your conditions — not the lab's.";

// chip is the one-tap correction label: the short, behavioral name the person taps
// to declare a different reading than the machine suggested (never an auto-disposition).
export const LOOP_STATE_COPY = {
  [LOOP_STATE_GAP_REVEALED]: {
    headline: "It answers when asked. It just didn't volunteer.",
    tag: "That's the Volunteer Gap — you just watched it happen in your own chat.",
    chip: "It didn't volunteer",
  },
  [LOOP_STATE_STILL_MISSING]: {
    headline: "You asked directly. It still didn't surface.",
    cta: "Push harder →",
    chip: "Still didn't surface",
  },
  [LOOP_STATE_NOT_CLEAR]: {
    headline: "The second answer changed. The gap isn't clean.",
    cta: "Try the cleaner check →", // shown only when the quick (same-chat) check was used
    swapPanels: true,
    chip: "Not clear yet",
  },
};

// ── Quick vs cleaner check (R1, item 5) ───────────────────────────────────────
// The person declares how they ran the second answer. Same chat is faster but the
// first answer is still in context; a fresh chat is a cleaner comparison. The
// choice is stored as declared metadata (never verified) and the reveal's small
// print reflects which was used.
export const CHECK_QUICK = "quick"; // same chat, the probe alone
export const CHECK_CLEANER = "cleaner"; // fresh chat, scenario + probe bundle
export const CHECK_CHOICE_COPY = "Same chat is faster. A fresh chat gives you a cleaner comparison.";
export const CHECK_QUICK_COPY = { label: "Quick check", hint: "Same chat. Paste the question, ask again." };
export const CHECK_CLEANER_COPY = { label: "Cleaner check", hint: "Fresh chat. Copy the setup, then ask." };

// The cleaner-check bundle for a FRESH chat: the original scenario (the open
// question) followed by the same fixed probe. Deterministic and line-ending
// normalized, exactly like buildTargetedPrompt, so it can be recorded verbatim.
export function buildCleanerBundle({ question } = {}) {
  const q = typeof question === "string" ? question.trim() : "";
  const lines = [];
  if (q) {
    lines.push(q);
    lines.push("");
  }
  lines.push(TARGETED_PROMPT_TEXT);
  return normalizeLineEndings(lines.join("\n")).trim();
}

// ── Run-the-pair v1: capture discipline + schema PairRun ──────────────────────
// The paste-back step records HOW the person ran the two answers, in loose voice,
// and derives one conservative flag — conditions_matched — that the schema PairRun
// (docs/REVIEW-GRAPH-SCHEMA.md §1) carries. Nothing here gates the loop: the reveal
// always completes. Disclosure marks how clean the capture was; it never decides
// whether the conditions lined up, and it can't suppress the warning when they
// didn't (the conditions_matched != true rule renders on every derived surface).
//
// Pure JS, like the rest of this module: no DOM, no storage, no model call. The
// client (workbench-app.jsx) collects the three inputs and calls buildPairCapture;
// the review record (reader-review-record.js) embeds the returned PairRun verbatim.

// Capture input enums — the three answers the paste-back form can yield. Anything
// outside these (including an unanswered/skipped question, undefined) is treated as
// unresolved, never as a positive claim in either direction.
export const PAIR_SAME_MODEL = { YES: "yes", NO: "no", NOT_SURE: "not_sure" };
export const PAIR_EDITS = { NONE: "none", EDITED: "edited" };
// The third conditions_matched state. true and false are booleans; unverified is
// this literal string, so the schema's `conditions_matched != true` rule catches
// BOTH a false and an unverified with one `!== true` comparison.
export const PAIR_CONDITIONS_UNVERIFIED = "unverified";
const PAIR_MODEL_VERSION_MAX = 80;

// Conservative derivation (the AT-12 truth table). FALSE WINS: any disclosed edit,
// or a different model, forces conditions_matched = false — an edited or cross-model
// pair was NOT run under matched conditions, whatever else was said. true is earned
// only by the one clean case: same model affirmed AND neither answer edited.
// Everything unresolved — "not sure", or a question left unanswered — is unverified,
// never invented as either matched or unmatched.
export function deriveConditionsMatched({ same_model, edits } = {}) {
  if (edits === PAIR_EDITS.EDITED) return false; // a disclosed edit is never matched
  if (same_model === PAIR_SAME_MODEL.NO) return false; // a different model is never matched
  if (same_model === PAIR_SAME_MODEL.YES && edits === PAIR_EDITS.NONE) return true;
  return PAIR_CONDITIONS_UNVERIFIED; // not sure / skipped / otherwise unresolved
}

// Build the schema PairRun.capture block from the three paste-back inputs. The two
// booleans project the disclosure; model_version_user_reported is OPTIONAL and
// carried only when the person supplied one (trimmed + capped so it stays short
// metadata, never a payload). conditions_matched is the conservative derivation.
export function buildPairCapture({ same_model, model_version, edits } = {}) {
  const capture = {
    same_model_claimed: same_model === PAIR_SAME_MODEL.YES,
    user_edits_disclosed: edits === PAIR_EDITS.EDITED,
    conditions_matched: deriveConditionsMatched({ same_model, edits }),
  };
  const version = typeof model_version === "string" ? model_version.trim() : "";
  if (version) capture.model_version_user_reported = version.slice(0, PAIR_MODEL_VERSION_MAX);
  return capture;
}

// The schema rule as a predicate: true when a capture's conditions did NOT come
// through as matched (conditions_matched != true). Every surface derived from a
// PairRun — the side-by-side view, the review record — keys the unmatched-conditions
// warning off this one function so the rule can never drift between surfaces.
export function pairConditionsUnmatched(capture) {
  return !capture || capture.conditions_matched !== true;
}

// Build the schema PairRun (mode = paired; the object's mere presence IS the paired
// mode marker per schema §1). The targeted prompt is the v1.1-style non-leading
// probe; the two artifact ids point at the stored-verbatim answers; the capture
// block carries the conservative conditions_matched flag. Deterministic — no time,
// no randomness — so a paired run records and hashes reproducibly.
export function buildPairRun({ targeted_prompt, original_artifact_id, targeted_artifact_id, capture } = {}) {
  return {
    targeted_prompt: typeof targeted_prompt === "string" ? targeted_prompt : "",
    original_artifact_id: typeof original_artifact_id === "string" ? original_artifact_id : "",
    targeted_artifact_id: typeof targeted_artifact_id === "string" ? targeted_artifact_id : "",
    capture: capture && typeof capture === "object" ? capture : {},
  };
}

// Loose-voice capture UI copy, single-sourced like the reveal copy above and covered
// by the AT-5 vocabulary lint. Pointer register: the warning points at HOW to read
// the side-by-side; it never renders a verdict on either answer.
export const PAIR_CAPTURE_UI = {
  heading: "One quick thing before the side-by-side",
  intro: "This just marks how you ran the two answers. It never changes what they say.",
  same_model: {
    question: "Did both answers come from the same AI — same provider, same model?",
    options: {
      [PAIR_SAME_MODEL.YES]: "Yes, the same one",
      [PAIR_SAME_MODEL.NO]: "No, a different one",
      [PAIR_SAME_MODEL.NOT_SURE]: "Not sure",
    },
  },
  model_version: {
    question: "Which model did you use? Optional.",
    hint: "The name or version, as you remember it.",
    placeholder: "e.g. the model or version you ran",
  },
  edits: {
    question: "Did you edit either answer before pasting?",
    options: {
      [PAIR_EDITS.NONE]: "No, neither was edited",
      [PAIR_EDITS.EDITED]: "Yes, I edited one or both",
    },
  },
  disclosure: "This marks how clean the capture was. It doesn't decide whether the conditions lined up.",
  unmatched_warning:
    "The conditions behind these two answers aren't confirmed as matched — a different model, an edit, or a setup you weren't sure about. Read the side-by-side as a looser comparison, not a like-for-like.",
  unmatched_badge: "Unmatched conditions",
};
